### ISSUE TITLE
🐛 Image jellyfin:10.8.13 does not exist

### ISSUE THREAD

**Issue by djjudas21** [beluga-cloud/charts#284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Application name

jellyfin

### Application version

2.3.0

### Current behavior

Helm chart jellyfin 2.3.0 references the image `jellyfin:10.8.13`, which doesn't exist. Deploying with this Helm chart results a Kubernetes error:

```
[jonathan@poseidon jellyfin]$ kubectl get po
NAME         READY   STATUS             RESTARTS   AGE
jellyfin-0   0/1     ImagePullBackOff   0          2d20h
```

```
[jonathan@poseidon jellyfin]$ kubectl events
LAST SEEN                TYPE     REASON    OBJECT           MESSAGE
3m14s (x6940 over 26h)   Normal   BackOff   Pod/jellyfin-0   Back-off pulling image "ghcr.io/beluga-cloud/jellyfin/jellyfin:10.8.13"
```

### Expected behavior

I expect the Helm chart to reference a valid image, so Kubernetes can pull the image successfully

### Steps to reproduce

```
helm secrets upgrade -i --create-namespace \
    -n jellyfin jellyfin \
    -f values.yaml \
    beluga-cloud/jellyfin
```
My `values.yaml` doesn't contain any overrides related to the image registry or tags

```
[jonathan@poseidon jellyfin]$ helm ls
NAME    	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART         	APP VERSION
jellyfin	jellyfin 	9       	2023-12-22 15:37:38.444619216 +0000 UTC	deployed	jellyfin-2.3.0	10.8.13    
```

### Other information

Probably just needs `ghcr.io/beluga-cloud/jellyfin/jellyfin:10.8.13` to be build or pushed again

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xunleii** [comment]
Hi @djjudas21, thanks for this issue.

I have seen but the workflow that built Jellyfin failed the last time, when I merged it to master. I need to improve my workflow to avoid this kind of issues.

Should be fixed now _(I build the images through the CI but build the manifest manually, so it has been signed with my account, cf. https://github.com/beluga-cloud/charts/actions/runs/7307007793)_

**Comment by djjudas21** [comment]
Thanks, this is working now 🎉
