### ISSUE TITLE
🐛 Jellyfind volume mounts incorrect

### ISSUE THREAD

**Issue by cfis** [beluga-cloud/charts#301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Application name

Jellyfin

### Application version

2.3.0

### Current behavior

When you stop and restart a Jellyfin container in Kubernetes all configuration is lost when using Persistent Volumes

### Expected behavior

Configuration should be kept across reboots

### Steps to reproduce

Configure config and data to use PVCs/PVs. Setup Jellyfin. Note no files are written to config or data PVs. Force restart the container. All config information is lost

### Related code

The problem is that the helm chart is mounting data to `/opt/jellyfin/config` and `/opt/jellyfin/data`. But Jellyfin instead is using '/config' inside the container.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cfis** [comment]
Ah, I see. I tried withe Jellyf image in the repository but that didn't work so I used a stock one.

Thanks!

**Comment by xunleii** [comment]
If you want, I can try to troubleshoot why the image in this repository didn't work for you.

**Comment by cfis** [comment]
Thanks for your offer to help xunleii, but I'm good!
